import Player from "./player";
import PropertyCard from "./cards/property-card";
import UtilitiesCard from "./cards/utilities-card";
import RailroadsCard from "./cards/railroads-card";
import CommunityChestCard from "./cards/community-chest-card";
import ChanceCard from "./cards/chance-card";

class Board {
  tokens: Array<{name: string}>;
  houses: number;
  hotels: number;
  doubleCount: number;
  currentDice: Array<number>;
  currentPlayer: Player;
  players: Array<Player>;
  propertyCards: Array<PropertyCard>;
  utilitiesCards: Array<UtilitiesCard>;
  railroadsCards: Array<RailroadsCard>;
  communityChestCards: Array<CommunityChestCard>;
  chanceCards: Array<ChanceCard>;
  tiles: Array<any>;
  cmpsOrder: Array<string>;

  constructor(players: Array<Player>) {
    this.tokens =  [
      {
        name: 'Scottish Terrier',
      },
      {
        name: 'Battleship',
      },
      {
        name: 'race car mid',
      },
      {
        name: 'Top Hat',
      },
      {
        name: 'Penguin',
      },
      {
        name: 'T-Rex',
      },
      {
        name: 'Cat',
      },
      {
        name: 'Rubber Ducky',
      },
    ];
    this.tiles = [
      {
        name: 'Go',
        players,
        owner: null,
        price: 60,
        type: 'go',
      },
      {
        name: 'Mediterranean Avenue',
        players: [],
        owner: null,
        color: '#562e22',
        price: 60,
        type: 'city',
      },
      {
        name: 'Community chest',
        players: [],
        owner: null,
        color: '',
        type: 'communityChest',
      },
      {
        name: 'Baltic Avenue',
        players: [],
        owner: null,
        color: '#562e22',
        price: 60,
        type: 'city',
      },
      {
        name: 'Income tax',
        players: [],
        owner: null,
        color: '',
        price: 200,
        type: 'tax',
      },
      {
        name: 'Reading Railroad',
        players: [],
        owner: null,
        color: '',
        price: 200,
        type: 'railroad',
      },
      {
        name: 'Oriental Avenue',
        players: [],
        owner: null,
        color: '#95b8cb',
        price: 100,
        type: 'city',
      },
      {
        name: 'Chance',
        players: [],
        owner: null,
        type: 'chance',
      },
      {
        name: 'Vermont Avenue',
        players: [],
        owner: null,
        color: '#95b8cb',
        price: 100,
        type: 'city',
      },
      {
        name: 'Connecticut Avenue',
        players: [],
        owner: null,
        color: '#95b8cb',
        price: 120,
        type: 'city',
      },
      {
        name: 'jail',
        players: [],
        owner: null,
        type: 'visit',
      },
      {
        name: 'St. Charles Place',
        players: [],
        owner: null,
        color: '#cb5382',
        price: 140,
        type: 'city',
      },
      {
        name: 'Electric Company',
        players: [],
        owner: null,
        color: '',
        price: 140,
        type: 'utility',
      },
      {
        name: 'States Avenue',
        players: [],
        owner: null,
        color: '#cb5382',
        price: 140,
        type: 'city',
      },
      {
        name: 'Virginia Avenue',
        players: [],
        owner: null,
        color: '#cb5382',
        price: 160,
        type: 'city',
      },
      {
        name: 'Pennsylvania Railroad',
        players: [],
        owner: null,
        color: '',
        price: 200,
        type: 'railroad',
      },
      {
        name: 'St. James Place',
        players: [],
        owner: null,
        color: '#ffa600',
        price: 100,
        type: 'city',
      },
      {
        name: 'Community chest',
        players: [],
        owner: null,
        type: 'communityChest',
      },
      {
        name: 'Tennessee Avenue',
        players: [],
        owner: null,
        color: '#ffa600',
        price: 180,
        type: 'city',
      },
      {
        name: 'New York Avenue',
        players: [],
        owner: null,
        color: '#ffa600',
        price: 200,
        type: 'city',
      },

      {
        name: 'Parking',
        players: [],
        owner: null,
        color: '',
        type: 'parking',
      },
      {
        name: 'Kentucky Avenue',
        players: [],
        owner: null,
        color: '#cf3b30',
        price: 220,
        type: 'city',
      },
      {
        name: 'Chance',
        players: [],
        owner: null,
        color: '',
        type: 'chance',
      },
      {
        name: 'Indiana Avenue',
        players: [],
        owner: null,
        color: '#cf3b30',
        price: 220,
        type: 'city',
      },
      {
        name: 'Illinois Avenue',
        players: [],
        owner: null,
        color: '#cf3b30',
        price: 240,
        type: 'city',
      },
      {
        name: 'B. & O. Railroad',
        players: [],
        owner: null,
        color: '',
        price: 200,
        type: 'railroad',
      },
      {
        name: 'Atlantic Avenue',
        players: [],
        owner: null,
        color: '#d3c11b',
        price: 260,
        type: 'city',
      },
      {
        name: 'Ventnor Avenue',
        players: [],
        owner: null,
        color: '#d3c11b',
        price: 260,
        type: 'city',
      },
      {
        name: 'Water  Works',
        players: [],
        owner: null,
        color: '',
        price: 100,
        type: 'utility',
      },

      {
        name: 'Marvin Gardens',
        players: [],
        owner: null,
        color: '#d3c11b',
        price: 280,
        type: 'city',
      },
      {
        name: 'Send To Jail',
        players: [],
        owner: null,
        color: '',
        type: 'jail',
      },
      {
        name: 'Pacific Avenue',
        players: [],
        owner: null,
        color: '#0ab842',
        price: 300,
        type: 'city',
      },
      {
        name: 'North Carolina Avenue',
        players: [],
        owner: null,
        color: '#0ab842',
        price: 300,
        type: 'city',
      },
      {
        name: 'Community chest',
        players: [],
        owner: null,
        color: '',
        type: 'communityChest',
      },
      {
        name: 'Pennsylvania Avenue',
        players: [],
        owner: null,
        color: '#0ab842',
        price: 320,
        type: 'city',
      },
      {
        name: 'Short Line',
        players: [],
        owner: null,
        color: '',
        price: 200,
        type: 'railroad',
      },
      {
        name: 'Chance',
        players: [],
        owner: null,
        color: '',
        type: 'chance',
      },
      {
        name: 'Park Place',
        players: [],
        owner: null,
        color: '#2863ad',
        price: 350,
        type: 'city',
      },
      {
        name: 'Luxury Tax',
        players: [],
        owner: null,
        color: '',
        price: 75,
        type: 'tax',
      },
      {
        name: 'Boardwalk',
        players: [],
        owner: null,
        color: '#2863ad',
        price: 400,
        type: 'city',
      },
    ];
    this.cmpsOrder =  [
      'startCmp',
      'tileCmp',
      'communityCmp',
      'tileCmp',
      'incomeCmp',
      'railroadCmp',
      'tileCmp',
      'chanceCmp',
      'tileCmp',
      'tileCmp',
      'jailCmp',
      'tileCmp',
      'electricCmp',
      'tileCmp',
      'tileCmp',
      'railroadCmp',
      'tileCmp',
      'communityCmp',
      'tileCmp',
      'tileCmp',
      'parkingCmp',
      'tileCmp',
      'chanceCmp',
      'tileCmp',
      'tileCmp',
      'railroadCmp',
      'tileCmp',
      'tileCmp',
      'waterWorkCmp',
      'tileCmp',
      'sendToJailCmp',
      'tileCmp',
      'tileCmp',
      'communityCmp',
      'tileCmp',
      'railroadCmp',
      'chanceCmp',
      'tileCmp',
      'luxuryTaxCmp',
      'tileCmp',
    ];
    this.propertyCards =  [
      new PropertyCard(
        'property-101',
        'Mediterranean Avenue',
        '#562e22',
        60,
        2,
        10,
        30,
        90,
        160,
        250,
        30,
        50,
        210,
        50,
        'propertyCard',
        2,
        0,
        0)
      ,
      new PropertyCard(
        'property-102',
        'Baltic Avenue',
        '#562e22',
        60,
        4,
        20,
        60,
        180,
        320,
        450,
        30,
        50,
        370,
        50,
        'propertyCard',
        2,
        0,
        0,
      ),
      new PropertyCard(
        'property-103',
        'Oriental Avenue',
        '#95b8cb',
        100,
        6,
        30,
        90,
        270,
        400,
        550,
        50,
        50,
        450,
        50,
        'propertyCard',
        3,
        0,
        0,
      ),
      new PropertyCard(
        'property-104',
        'Vermont Avenue',
        '#95b8cb',
        100,
        6,
        30,
        90,
        270,
        400,
        550,
        50,
        50,
        450,
        50,
        'propertyCard',
        3,
        0,
        0,
      ),
      new PropertyCard(
        'property-105',
        'Connecticut Avenue',
        '#95b8cb',
        120,
        8,
        40,
        100,
        300,
        450,
        600,
        60,
        50,
        500,
        50,
        'propertyCard',
        3,
        0,
        0,
      ),
      new PropertyCard(
        'property-106',
        'St. Charles Place',
        '#cb5382',
        140,
        10,
        50,
        150,
        450,
        625,
        750,
        70,
        100,
        725,
        50,
        'propertyCard',
        3,
        0,
        0,
      ),
      new PropertyCard(
        'property-107',
        'States Avenue',
        '#cb5382',
        140,
        10,
        50,
        150,
        450,
        625,
        750,
        70,
        100,
        725,
        50,
        'propertyCard',
        3,
        0,
        0,
      ),
      new PropertyCard(
        'property-108',
        'Virginia Avenue',
        '#cb5382',
        160,
        12,
        60,
        180,
        500,
        700,
        900,
        80,
        100,
        800,
        50,
        'propertyCard',
        3,
        0,
        0,
      ),
      new PropertyCard(
        'property-109',
        'St. James Place',
        '#ffa600',
        100,
        14,
        70,
        200,
        550,
        750,
        950,
        90,
        100,
        850,
        50,
        'propertyCard',
        3,
        0,
        0,
      ),
      new PropertyCard(
        'property-110',
        'Tennessee Avenue',
        '#ffa600',
        180,
        14,
        70,
        200,
        550,
        750,
        950,
        90,
        100,
        850,
        50,
        'propertyCard',
        3,
        0,
        0,
      ),
      new PropertyCard(
        'property-111',
        'New York Avenue',
        '#ffa600',
        200,
        16,
        80,
        220,
        600,
        800,
        1000,
        100,
        100,
        900,
        50,
        'propertyCard',
        3,
        0,
        0,
      ),
      new PropertyCard(
        'property-112',
        'Kentucky Avenue',
        '#cf3b30',
        220,
        18,
        90,
        250,
        700,
        875,
        1050,
        110,
        150,
        1025,
        150,
        'propertyCard',
        3,
        0,
        0,
      ),
      new PropertyCard(
        'property-113',
        'Indiana Avenue',
        '#cf3b30',
        220,
        18,
        90,
        250,
        700,
        875,
        1050,
        110,
        150,
        1025,
        150,
        'propertyCard',
        3,
        0,
        0,
      ),
      new PropertyCard(
        'property-114',
        'Illinois Avenue',
        '#cf3b30',
        240,
        20,
        100,
        300,
        750,
        925,
        1100,
        120,
        150,
        1075,
        150,
        'propertyCard',
        3,
        0,
        0,
      ),
      new PropertyCard(
        'property-115',
        'Atlantic Avenue',
        '#d3c11b',
        260,
        22,
        110,
        330,
        800,
        975,
        1150,
        130,
        150,
        1125,
        150,
        'propertyCard',
        3,
        0,
        0,
      ),
      new PropertyCard(
        'property-116',
        'Ventnor Avenue',
        '#d3c11b',
        260,
        22,
        110,
        330,
        800,
        975,
        1150,
        130,
        150,
        1125,
        150,
        'propertyCard',
        3,
        0,
        0,
      ),
      new PropertyCard(
        'property-117',
        'Marvin Gardens',
        '#d3c11b',
        280,
        24,
        120,
        360,
        850,
        1025,
        1200,
        140,
        150,
        1175,
        150,
        'propertyCard',
        3,
        0,
        0,
      ),
      new PropertyCard(
        'property-118',
        'Pacific Avenue',
        '#0ab842',
        300,
        26,
        130,
        390,
        900,
        1100,
        1275,
        150,
        200,
        1300,
        200,
        'propertyCard',
        3,
        0,
        0,
      ),
      new PropertyCard(
        'property-119',
        'North Carolina Avenue',
        '#0ab842',
        300,
        26,
        130,
        390,
        900,
        1100,
        1275,
        150,
        200,
        1300,
        200,
        'propertyCard',
        3,
        0,
        0,
      ),
      new PropertyCard(
        'property-120',
        'Pennsylvania Avenue',
        '#0ab842',
        320,
        28,
        150,
        450,
        1000,
        1200,
        1400,
        160,
        200,
        1400,
        200,
        'propertyCard',
        3,
        0,
        0,
      ),
      new PropertyCard(
        'property-121',
        'Park Place',
        '#2863ad',
        350,
        35,
        175,
        500,
        1100,
        1300,
        1500,
        170,
        200,
        1500,
        200,
        'propertyCard',
        2,
        0,
        0,
      ),
      new PropertyCard(
        'property-122',
        'Boardwalk',
        '#2863ad',
        400,
        50,
        200,
        600,
        1400,
        1700,
        2000,
        200,
        200,
        1900,
        200,
        'propertyCard',
        2,
        0,
        0,
      ),
    ];
    this.utilitiesCards =  [
      new UtilitiesCard(
        'utility-101',
        'Electric Company',
        140,
        '4 * Dice Roll',
        '10 * Dice Roll',
        75,
        '#cf8e61',
        'utilityCard',
      ),
      new UtilitiesCard(
        'utility-102',
        'Waterworks',
        100,
        '4 * Dice Roll',
        '10 * Dice Roll',
        75,
        '#f6f4f4',
        'utilityCard',
      ),
    ];
    this.railroadsCards =  [
      new RailroadsCard(
        'railroad-101',
        'Reading Railroad',
        '',
        200,
        25,
        50,
        100,
        200,
        100,
        'railroadCard',
      ),
      new RailroadsCard(
        'railroad-102',
        'Pennsylvania Railroad',
        '',
        200,
        25,
        50,
        100,
        200,
        100,
        'railroadCard',
      ),
      new RailroadsCard(
        'railroad-103',
        'B. & O. Railroad',
        '',
        200,
        25,
        50,
        100,
        200,
        100,
        'railroadCard',
      ),
      new RailroadsCard(
        'railroad-104',
        'Short Line',
        '',
        200,
        25,
        50,
        100,
        200,
        100,
        'railroadCard',
      ),
    ];
    this.communityChestCards =  [
      new CommunityChestCard(
        'community-101',
        'Community Chest',
        'Advance to "Go". (Collect $200) ',
        '#ffeb43',
        'communityChestCard',
      ),
      new CommunityChestCard(
        'community-102',
        'Community Chest',
        'Life insurance matures - Collect $100',
        '#ffeb43',
        'communityChestCard',
      ),
      new CommunityChestCard(
        'community-103',
        'Community Chest',
        'Get Out of Jail Free. ',
        '#ffeb43',
        'communityChestCard',
      ),
      new CommunityChestCard(
        'community-104',
        'Community Chest',
        'You have won second prize in a beauty contest. Collect $10.',
        '#ffeb43',
        'communityChestCard',
      ),
      new CommunityChestCard(
        'community-105',
        'Community Chest',
        'Bank error in your favor. Collect $200. ',
        '#ffeb43',
        'communityChestCard',
      ),
      new CommunityChestCard(
        'community-106',
        'Community Chest',
        'From sale of stock you get $50.',
        '#ffeb43',
        'communityChestCard',
      ),
      new CommunityChestCard(
        'community-107',
        'Community Chest',
        'Income tax refund. Collect $20. ',
        '#ffeb43',
        'communityChestCard',
      ),
      new CommunityChestCard(
        'community-108',
        'Community Chest',
        'Receive for services $25.',
        '#ffeb43',
        'communityChestCard',
      ),
      new CommunityChestCard(
        'community-109',
        'Community Chest',
        'You inherit $100.',
        '#ffeb43',
        'communityChestCard',
      ),
      new CommunityChestCard(
        'community-110',
        'Community Chest',
        'Holiday Fund matures. Collect $100. ',
        '#ffeb43',
        'communityChestCard',
      ),
      new CommunityChestCard(
        'community-111',
        'Community Chest',
        'Collect $50 from every player for opening night seats. ',
        '#ffeb43',
        'communityChestCard',
      ),
      new CommunityChestCard(
        'community-112',
        'Community Chest',
        "Doctor's fees. Pay $50.",
        '#ffeb43',
        'communityChestCard',
      ),
      new CommunityChestCard(
        'community-113',
        'Community Chest',
        'Pay hospital $100.',
        '#ffeb43',
        'communityChestCard',
      ),
      new CommunityChestCard(
        'community-114',
        'Community Chest',
        'Pay school tax of $150',
        '#ffeb43',
        'communityChestCard',
      ),
      new CommunityChestCard(
        'community-115',
        'Community Chest',
        'You are assessed for street repairs: Pay $40 per house and $115 per hotel you own. ',
        '#ffeb43',
        'communityChestCard',
      ),
      new CommunityChestCard(
        'community-116',
        'Community Chest',
        'Go to Jail. ',
        '#ffeb43',
        'communityChestCard',
      ),
    ];
    this.chanceCards =  [
      new ChanceCard(
        'chance-201',
        'Chance',
        'Advance to "Go". (Collect $200).',
        '#ff5c00',
        'chanceCards',
      ),
      new ChanceCard(
        'chance-202',
        'Chance',
        'Advance to Illinois Ave. {Avenue}. If you pass Go, collect $200.',
        '#ff5c00',
        'chanceCards',
      ),
      new ChanceCard(
        'chance-203',
        'Chance',
        'Advance to St. Charles Place. If you pass Go, collect $200. ',
        '#ff5c00',
        'chanceCards',
      ),
      new ChanceCard(
        'chance-204',
        'Chance',
        'Advance token to the nearest Utility. If unowned, you may buy it from the Bank. If owned, throw dice and pay owner a total 10 (ten) times the amount thrown. ',
        '#ff5c00',
        'chanceCards',
      ),
      new ChanceCard(
        'chance-205',
        'Chance',
        'Advance to the nearest Railroad. If unowned, you may buy it from the Bank. If owned, pay owner twice the re tal to which they are otherwise entitled. If Railroad is unowned, you may buy it from the Bank.',
        '#ff5c00',
        'chanceCards',
      ),
      new ChanceCard(
        'chance-206',
        'Chance',
        'Bank pays you dividend of $50. ',
        '#ff5c00',
        'chanceCards',
      ),
      new ChanceCard(
        'chance-207',
        'Chance',
        'Get out of Jail Free.',
        '#ff5c00',
        'chanceCards',
      ),
      new ChanceCard(
        'chance-208',
        'Chance',
        'Go Back 3 Spaces.',
        '#ff5c00',
        'chanceCards',
      ),
      new ChanceCard(
        'chance-209',
        'Chance',
        'Go to Jail. Go directly to Jail. Do not pass GO, do not collect $200.',
        '#ff5c00',
        'chanceCards',
      ),
      new ChanceCard(
        'chance-210',
        'Chance',
        'Make general repairs on all your property: For each house pay $25, For each hotel {pay} $100.',
        '#ff5c00',
        'chanceCards',
      ),
      new ChanceCard(
        'chance-211',
        'Chance',
        'Pay poor tax of $15',
        '#ff5c00',
        'chanceCards',
      ),
      new ChanceCard(
        'chance-212',
        'Chance',
        'Take a trip to Reading Railroad.  If you pass Go, collect $200. ',
        '#ff5c00',
        'chanceCards',
      ),
      new ChanceCard(
        'chance-213',
        'Chance',
        'Take a walk on the Boardwalk. Advance token to Boardwalk. ',
        '#ff5c00',
        'chanceCards',
      ),
      new ChanceCard(
        'chance-214',
        'Chance',
        'You have been elected Chairman of the Board. Pay each player $50. ',
        '#ff5c00',
        'chanceCards',
      ),
      new ChanceCard(
        'chance-215',
        'Chance',
        'Your building {and} loan matures. Receive {Collect} $150.',
        '#ff5c00',
        'chanceCards',
      ),
      new ChanceCard(
        'chance-216',
        'Chance',
        'You have won a crossword competition. Collect $100.',
        '#ff5c00',
        'chanceCards',
      ),
    ];
    this.houses = 32;
    this.hotels = 12;
    this.doubleCount = 0;
    this.currentPlayer = players[0];
    this.players = players;
    this.currentDice = new Array<number>();
  }
}

export default Board;