import {Tile} from "./Tiles/Tile";
import {GoTile} from "./Tiles/GoTile";
import {CityTile} from "./Tiles/CityTile";
import {CommunityChestTile} from "./Tiles/CommunityChestTile";
import {TaxTile} from "./Tiles/TaxTile";
import {RailroadTile} from "./Tiles/RailroadTile";
import {ChanceTile} from "./Tiles/ChanceTile";
import {VisitTile} from "./Tiles/VisitTile";
import {UtilityTile} from "./Tiles/UtilityTile";
import {ParkingTile} from "./Tiles/ParkingTile";
import {JailTile} from "./Tiles/JailTile";
import {Player} from "./Player";
import {PropertyCard} from "./Cards/PropertyCard";
import {UtilitiesCard} from "./Cards/UtilitiesCard";
import {RailroadsCard} from "./Cards/RailroadsCard";
import {CommunityChest} from "./Cards/CommunityChest";
import {ChanceCard} from "./Cards/ChanceCard";

export const tokens = Object.freeze( [
  {
    name: 'Scottish Terrier',
  },
  {
    name: 'Battleship',
  },
  {
    name: 'race car mid',
  },
  {
    name: 'Top Hat',
  },
  {
    name: 'Penguin',
  },
  {
    name: 'T-Rex',
  },
  {
    name: 'Cat',
  },
  {
    name: 'Rubber Ducky',
  },
]);

export const cmpsOrder = Object.freeze([
  'startCmp',
  'tileCmp',
  'communityCmp',
  'tileCmp',
  'incomeCmp',
  'railroadCmp',
  'tileCmp',
  'chanceCmp',
  'tileCmp',
  'tileCmp',
  'jailCmp',
  'tileCmp',
  'electricCmp',
  'tileCmp',
  'tileCmp',
  'railroadCmp',
  'tileCmp',
  'communityCmp',
  'tileCmp',
  'tileCmp',
  'parkingCmp',
  'tileCmp',
  'chanceCmp',
  'tileCmp',
  'tileCmp',
  'railroadCmp',
  'tileCmp',
  'tileCmp',
  'waterWorkCmp',
  'tileCmp',
  'sendToJailCmp',
  'tileCmp',
  'tileCmp',
  'communityCmp',
  'tileCmp',
  'railroadCmp',
  'chanceCmp',
  'tileCmp',
  'luxuryTaxCmp',
  'tileCmp',
]);

export function getTiles(players: Array<Player>): Array<Tile> {
  return  [
    new GoTile(
      'Go',
      players,
      null,
      60,
    ),
    new CityTile(
      'Mediterranean Avenue',
      [],
      null,
      60,
    ),
    new CommunityChestTile(
      'Community chest',
      [],
      null,
    ),
    new CityTile(
      'Baltic Avenue',
      [],
      null,
      60,
    ),
    new TaxTile(
      'Income tax',
      [],
      null,
      200,
    ),
    new RailroadTile(
      'Reading Railroad',
      [],
      null,
      200,
    ),
    new CityTile(
      'Oriental Avenue',
      [],
      null,
      100,
    ),
    new ChanceTile(
      'Chance',
      [],
      null,
    ),
    new CityTile(
      'Vermont Avenue',
      [],
      null,
      100,
    ),
    new CityTile(
      'Connecticut Avenue',
      [],
      null,
      120,
    ),
    new VisitTile(
      'jail',
      [],
      null,
    ),
    new CityTile(
      'St. Charles Place',
      [],
      null,
      140,
    ),
    new UtilityTile(
      'Electric Company',
      [],
      null,
      140,
    ),
    new CityTile(
      'States Avenue',
      [],
      null,
      140,
    ),
    new CityTile(
      'Virginia Avenue',
      [],
      null,
      160,
    ),
    new RailroadTile(
      'Pennsylvania Railroad',
      [],
      null,
      200,
    ),
    new CityTile(
      'St. James Place',
      [],
      null,
      100,
    ),
    new CommunityChestTile(
      'Community chest',
      [],
      null,
    ),
    new CityTile(
      'Tennessee Avenue',
      [],
      null,
      180,
    ),
    new CityTile(
      'New York Avenue',
      [],
      null,
      200,
    ),
    new ParkingTile(
      'Parking',
      [],
      null,
    ),
    new CityTile(
      'Kentucky Avenue',
      [],
      null,
      220,
    ),
    new ChanceTile(
      'Chance',
      [],
      null,
    ),
    new CityTile(
      'Indiana Avenue',
      [],
      null,
      220,
    ),
    new CityTile(
      'Illinois Avenue',
      [],
      null,
      240,
    ),
    new RailroadTile(
      'B. & O. Railroad',
      [],
      null,
      200,
    ),
    new CityTile(
      'Atlantic Avenue',
      [],
      null,
      260,
    ),
    new CityTile(
      'Ventnor Avenue',
      [],
      null,
      260,
    ),
    new UtilityTile(
      'Water  Works',
      [],
      null,
      100,
    ),
    new CityTile(
      'Marvin Gardens',
      [],
      null,
      280,
    ),
    new JailTile(
      'Send To Jail',
      [],
      null,
    ),
    new CityTile(
      'Pacific Avenue',
      [],
      null,
      300,
    ),
    new CityTile(
      'North Carolina Avenue',
      [],
      null,
      300,
    ),
    new CommunityChestTile(
      'Community chest',
      [],
      null,
    ),
    new CityTile(
      'Pennsylvania Avenue',
      [],
      null,
      320,
    ),
    new RailroadTile(
      'Short Line',
      [],
      null,
      200,
    ),
    new ChanceTile(
      'Chance',
      [],
      null,
    ),
    new CityTile(
      'Park Place',
      [],
      null,
      350,
    ),
    new TaxTile(
      'Luxury Tax',
      [],
      null,
      75,
    ),
    new CityTile(
      'Boardwalk',
      [],
      null,
      400,
    ),
  ];
}

export function getPropertyCards(): Array<PropertyCard> {
  return  [
    new PropertyCard(
      'property-101',
      'Mediterranean Avenue',
      60,
      2,
      10,
      30,
      90,
      160,
      250,
      30,
      50,
      210,
      2,
      0,
      0)
    ,
    new PropertyCard(
      'property-102',
      'Baltic Avenue',
      60,
      4,
      20,
      60,
      180,
      320,
      450,
      30,
      50,
      370,
      2,
      0,
      0,
    ),
    new PropertyCard(
      'property-103',
      'Oriental Avenue',
      100,
      6,
      30,
      90,
      270,
      400,
      550,
      50,
      50,
      450,
      3,
      0,
      0,
    ),
    new PropertyCard(
      'property-104',
      'Vermont Avenue',
      100,
      6,
      30,
      90,
      270,
      400,
      550,
      50,
      50,
      450,
      3,
      0,
      0,
    ),
    new PropertyCard(
      'property-105',
      'Connecticut Avenue',
      120,
      8,
      40,
      100,
      300,
      450,
      600,
      60,
      50,
      500,
      3,
      0,
      0,
    ),
    new PropertyCard(
      'property-106',
      'St. Charles Place',
      140,
      10,
      50,
      150,
      450,
      625,
      750,
      70,
      100,
      725,
      3,
      0,
      0,
    ),
    new PropertyCard(
      'property-107',
      'States Avenue',
      140,
      10,
      50,
      150,
      450,
      625,
      750,
      70,
      100,
      725,
      3,
      0,
      0,
    ),
    new PropertyCard(
      'property-108',
      'Virginia Avenue',
      160,
      12,
      60,
      180,
      500,
      700,
      900,
      80,
      100,
      800,
      3,
      0,
      0,
    ),
    new PropertyCard(
      'property-109',
      'St. James Place',
      100,
      14,
      70,
      200,
      550,
      750,
      950,
      90,
      100,
      850,
      3,
      0,
      0,
    ),
    new PropertyCard(
      'property-110',
      'Tennessee Avenue',
      180,
      14,
      70,
      200,
      550,
      750,
      950,
      90,
      100,
      850,
      3,
      0,
      0,
    ),
    new PropertyCard(
      'property-111',
      'New York Avenue',
      200,
      16,
      80,
      220,
      600,
      800,
      1000,
      100,
      100,
      900,
      3,
      0,
      0,
    ),
    new PropertyCard(
      'property-112',
      'Kentucky Avenue',
      220,
      18,
      90,
      250,
      700,
      875,
      1050,
      110,
      150,
      1025,
      3,
      0,
      0,
    ),
    new PropertyCard(
      'property-113',
      'Indiana Avenue',
      220,
      18,
      90,
      250,
      700,
      875,
      1050,
      110,
      150,
      1025,
      3,
      0,
      0,
    ),
    new PropertyCard(
      'property-114',
      'Illinois Avenue',
      240,
      20,
      100,
      300,
      750,
      925,
      1100,
      120,
      150,
      1075,
      3,
      0,
      0,
    ),
    new PropertyCard(
      'property-115',
      'Atlantic Avenue',
      260,
      22,
      110,
      330,
      800,
      975,
      1150,
      130,
      150,
      1125,
      3,
      0,
      0,
    ),
    new PropertyCard(
      'property-116',
      'Ventnor Avenue',
      260,
      22,
      110,
      330,
      800,
      975,
      1150,
      130,
      150,
      1125,
      3,
      0,
      0,
    ),
    new PropertyCard(
      'property-117',
      'Marvin Gardens',
      280,
      24,
      120,
      360,
      850,
      1025,
      1200,
      140,
      150,
      1175,
      3,
      0,
      0,
    ),
    new PropertyCard(
      'property-118',
      'Pacific Avenue',
      300,
      26,
      130,
      390,
      900,
      1100,
      1275,
      150,
      200,
      1300,
      3,
      0,
      0,
    ),
    new PropertyCard(
      'property-119',
      'North Carolina Avenue',
      300,
      26,
      130,
      390,
      900,
      1100,
      1275,
      150,
      200,
      1300,
      3,
      0,
      0,
    ),
    new PropertyCard(
      'property-120',
      'Pennsylvania Avenue',
      320,
      28,
      150,
      450,
      1000,
      1200,
      1400,
      160,
      200,
      1400,
      3,
      0,
      0,
    ),
    new PropertyCard(
      'property-121',
      'Park Place',
      350,
      35,
      175,
      500,
      1100,
      1300,
      1500,
      170,
      200,
      1500,
      2,
      0,
      0,
    ),
    new PropertyCard(
      'property-122',
      'Boardwalk',
      400,
      50,
      200,
      600,
      1400,
      1700,
      2000,
      200,
      200,
      1900,
      2,
      0,
      0,
    ),
  ];
}

export function getRailroadsCards(): Array<RailroadsCard> {
  return  [
    new RailroadsCard(
      'railroad-101',
      'Reading Railroad',
      '',
      200,
      25,
      50,
      100,
      200,
      100,
    ),
    new RailroadsCard(
      'railroad-102',
      'Pennsylvania Railroad',
      '',
      200,
      25,
      50,
      100,
      200,
      100,
    ),
    new RailroadsCard(
      'railroad-103',
      'B. & O. Railroad',
      '',
      200,
      25,
      50,
      100,
      200,
      100,
    ),
    new RailroadsCard(
      'railroad-104',
      'Short Line',
      '',
      200,
      25,
      50,
      100,
      200,
      100,
    ),
  ];
}

export function getCommunityChestCards(): Array<CommunityChest> {
  return  [
    new CommunityChest(
      'community-101',
      'Community Chest',
      'Advance to "Go". (Collect $200) ',
    ),
    new CommunityChest(
      'community-102',
      'Community Chest',
      'Life insurance matures - Collect $100',
    ),
    new CommunityChest(
      'community-103',
      'Community Chest',
      'Get Out of Jail Free. ',
    ),
    new CommunityChest(
      'community-104',
      'Community Chest',
      'You have won second prize in a beauty contest. Collect $10.',
    ),
    new CommunityChest(
      'community-105',
      'Community Chest',
      'Bank error in your favor. Collect $200. ',
    ),
    new CommunityChest(
      'community-106',
      'Community Chest',
      'From sale of stock you get $50.',
    ),
    new CommunityChest(
      'community-107',
      'Community Chest',
      'Income tax refund. Collect $20. ',
    ),
    new CommunityChest(
      'community-108',
      'Community Chest',
      'Receive for services $25.',
    ),
    new CommunityChest(
      'community-109',
      'Community Chest',
      'You inherit $100.',
    ),
    new CommunityChest(
      'community-110',
      'Community Chest',
      'Holiday Fund matures. Collect $100. ',
    ),
    new CommunityChest(
      'community-111',
      'Community Chest',
      'Collect $50 from every player for opening night seats. ',
    ),
    new CommunityChest(
      'community-112',
      'Community Chest',
      "Doctor's fees. Pay $50.",
    ),
    new CommunityChest(
      'community-113',
      'Community Chest',
      'Pay hospital $100.',
    ),
    new CommunityChest(
      'community-114',
      'Community Chest',
      'Pay school tax of $150',
    ),
    new CommunityChest(
      'community-115',
      'Community Chest',
      'You are assessed for street repairs: Pay $40 per house and $115 per hotel you own. ',
    ),
    new CommunityChest(
      'community-116',
      'Community Chest',
      'Go to Jail. ',
    ),
  ];
}

export function getUtilitiesCards(): Array<UtilitiesCard> {
  return  [
    new UtilitiesCard(
      'utility-101',
      'Electric Company',
      140,
      '4 * Dice Roll',
      '10 * Dice Roll',
      75,
    ),
    new UtilitiesCard(
      'utility-102',
      'Waterworks',
      100,
      '4 * Dice Roll',
      '10 * Dice Roll',
      75,
    ),
  ];
}

export function getChanceCards(): Array<ChanceCard> {
  return  [
    new ChanceCard(
      'chance-201',
      'Chance',
      'Advance to "Go". (Collect $200).',
    ),
    new ChanceCard(
      'chance-202',
      'Chance',
      'Advance to Illinois Ave. {Avenue}. If you pass Go, collect $200.',
    ),
    new ChanceCard(
      'chance-203',
      'Chance',
      'Advance to St. Charles Place. If you pass Go, collect $200. ',
    ),
    new ChanceCard(
      'chance-204',
      'Chance',
      'Advance token to the nearest Utility. If unowned, you may buy it from the Bank. If owned, throw dice and pay owner a total 10 (ten) times the amount thrown. ',
    ),
    new ChanceCard(
      'chance-205',
      'Chance',
      'Advance to the nearest Railroad. If unowned, you may buy it from the Bank. If owned, pay owner twice the re tal to which they are otherwise entitled. If Railroad is unowned, you may buy it from the Bank.',
    ),
    new ChanceCard(
      'chance-206',
      'Chance',
      'Bank pays you dividend of $50. ',
    ),
    new ChanceCard(
      'chance-207',
      'Chance',
      'Get out of Jail Free.',
    ),
    new ChanceCard(
      'chance-208',
      'Chance',
      'Go Back 3 Spaces.',
    ),
    new ChanceCard(
      'chance-209',
      'Chance',
      'Go to Jail. Go directly to Jail. Do not pass GO, do not collect $200.',
    ),
    new ChanceCard(
      'chance-210',
      'Chance',
      'Make general repairs on all your property: For each house pay $25, For each hotel {pay} $100.',
    ),
    new ChanceCard(
      'chance-211',
      'Chance',
      'Pay poor tax of $15',
    ),
    new ChanceCard(
      'chance-212',
      'Chance',
      'Take a trip to Reading Railroad.  If you pass Go, collect $200. ',
    ),
    new ChanceCard(
      'chance-213',
      'Chance',
      'Take a walk on the Boardwalk. Advance token to Boardwalk. ',
    ),
    new ChanceCard(
      'chance-214',
      'Chance',
      'You have been elected Chairman of the Board. Pay each player $50. ',
    ),
    new ChanceCard(
      'chance-215',
      'Chance',
      'Your building {and} loan matures. Receive {Collect} $150.',
    ),
    new ChanceCard(
      'chance-216',
      'Chance',
      'You have won a crossword competition. Collect $100.',
    ),
  ];
}