name: Build project to static
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build project to static in branch "build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@main
        with:
          node-version: 18.x
      - name: yarn install and build
        run: |
          yarn
          BASE_URL=https://monopoly-game.ostolex.com/ yarn build
      - name: Deploy to S3
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'dist'